### ISSUE TITLE
[Bug] search special char

### ISSUE THREAD

**Issue by 94noni** [lexik/LexikTranslationBundle#114]
Hi, 

There is a "bug" when searching string containing **'**

ex: here is the searched string
**L'INTERACTION** => error 500
**INTERACTION** => ok

**Comment by meglitis** [comment]
Quotes and other special symbols aren't esacped, so there is a sql injection possible. 

`vendor/lexik/translation-bundle/Lexik/Bundle/TranslationBundle/Entity/TransUnitRepository.php:210 $qb->andWhere($qb->expr()->like('t.content', sprintf("'%%%s%%'", $filters[$locale])));`

**Comment by cedric-g** [comment]
Hi, since v2.1.3 the parameters is set by using a query parameter: https://github.com/lexik/LexikTranslationBundle/blob/master/Entity/TransUnitRepository.php#L201-L202
