### ISSUE TITLE
Manage distributed systems

### ISSUE THREAD

**Issue by pharman** [lexik/LexikTranslationBundle#124]
I am integrating this bundle initially to use on our CMS. We have a cluster of servers which use one central database so I am currently integrating a message queue to handle cache expiry. It would be nice to be able to trigger a listener via configuration, to allow the integration to happen.

**Comment by pharman** [comment]
I have managed this by simply overriding the invalidate cache route. Simples.

**Comment by raziel057** [comment]
It's also possible to create a TranslationListener which check if a message has been updated since the last modification date of one of the cached catalog files.

Here is my TranslationListener:
```php
<?php
namespace My\Bundle\Listener;

use Symfony\Component\HttpKernel\Event\GetResponseEvent;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Translation\TranslatorInterface;
use Symfony\Component\Finder\Finder;
use Doctrine\ORM\EntityManagerInterface;

use Lexik\Bundle\TranslationBundle\Entity\File;

class TranslationListener implements EventSubscriberInterface
{
    /**
     * @var EntityManagerInterface
     */
    private $em = null;

    /**
     * @var TranslatorInterface
     */
    private $translator = null;

    /**
     * @var string
     */
    private $cacheDirectory = null;

    /**
     * @var array
     */
    private $managedLocales = null;

    /**
     * @var LoggerInterface
     */
    private $logger = null;

    /**
     * Constructor
     *
     * @param EntityManagerInterface $em
     * @param TranslatorInterface    $translator
     * @param string                 $cacheDirectory
     * @param array                  $managedLocales
     */
    public function __construct(EntityManagerInterface $em, TranslatorInterface $translator, $cacheDirectory, $managedLocales)
    {
        $this->em = $em;
        $this->cacheDirectory = $cacheDirectory;
        $this->translator = $translator;
        $this->managedLocales = $managedLocales;
    }

    /**
     * @param GetResponseEvent $event
     */
    public function onKernelRequest(GetResponseEvent $event)
    {
        if ($event->isMasterRequest()) {

            $qb = $this->em->createQueryBuilder();
            $qb->select('max(t.updatedAt)')
                ->from('LexikTranslationBundle:Translation', 't');

            $lastUpdateTime = $qb->getQuery()->getSingleScalarResult();

            $finder = new Finder();
            $finder->files()->in($this->cacheDirectory.'/translations')->date('< '.$lastUpdateTime);

            if ($finder->count() > 0) {
                $this->translator->removeLocalesCacheFiles($this->managedLocales);
            }
        }
    }

    static public function getSubscribedEvents()
    {
        return array(
            KernelEvents::REQUEST => array(array('onKernelRequest', 17)),
        );
    }
}
```

**Comment by pharman** [comment]
Nice idea @raziel057, I think this makes a lot more sense than the message queue

**Comment by raziel057** [comment]
@cedric-g What do you think about the integration of this listener in this bundle?

**Comment by cedric-g** [comment]
@raziel057 we can add an option (maybe false by default) to load and enable the listener.

**Comment by raziel057** [comment]
Make sense for me. We could add an ``auto_cache_clean`` parameter set to false by default. If this parameter is changed to yes the ``Invalidate cache`` button is not shown (because useless).

**Comment by cedric-g** [comment]
@raziel057 @pharman  I finally updated the `auto_clean_cache` branch (it's not merged in master yet).
If you want to check if it works on you app, just add the following option in your config file:
```yml
lexik_translation:
    auto_cache_clean: true
```

**Comment by raziel057** [comment]
@cedric-g Good Job! Thanks I will try it this week. Thanks for the implementation. I tried to implement the listener but couldn't test with the "document" implementation so I left aside.

I am pleased to see that you implemented it.

**Comment by raziel057** [comment]
@cedric-g I tried with Doctrine ORM implementation and it seems to works as expected! I think you can push it in master ;)

**Comment by cedric-g** [comment]
The PR has been merged, but not tagged yet.
