### ISSUE TITLE
Translations files - Read only 

### ISSUE THREAD

**Issue by rudzboy** [lexik/LexikTranslationBundle#131]
Logically in production environment, files located in src/MyBundle are not writable, so exporting these files or updating translations don't work either...

Is there any way to make this without modifying file access rules ?

Thx ;) Keep up the good work !

**Comment by cedric-g** [comment]
Hi, no you will need the right access rules. I think most of people use the export command in dev environment.

**Comment by rudzboy** [comment]
Ok, that's what I thought ;) Thx
