### ISSUE TITLE
[2.7] Filter grid on profiler token

### ISSUE THREAD

**Issue by rvanlaak** [lexik/LexikTranslationBundle#149]
Eversince the 2.7 release, the profiler has a new DataCollector that collects the messages that are and aren't translated. Will we be able to add a filter to the grid view, so it will become possible for translators to get all keys for a specific request? Maybe even make the last 10 request tokens clickable?

**Comment by Rvanlaak** [comment]
The `TranslationDataCollector` will be able to match the messages against the ones from the database easily:

```php
# <baseUrl>/translation/grid?token=90462c

/** @var TranslationDataCollector $collector */
$collector = $this->container->get('profiler')->loadProfile( $request->query->get('token') )->getCollector('translation');
```

The Collector has an array with messages that looks like:

```
TranslationDataCollector {#1309 ▼
  -translator: null
  #data: array:4 [▼
    0 => 51
    1 => 0
    2 => 0
    "messages" => array:51 [▼
      "nlLexikTranslationBundletranslations.page_title" => array:6 [▼
        "locale" => "nl"
        "domain" => "LexikTranslationBundle"
        "id" => "translations.page_title"
        "translation" => "Vertalingen"
        "state" => 0
        "count" => 2
      ]
      "nladminbackendshortcuts.show_shortcuts" => array:6 [▼
        "locale" => "nl"
        "domain" => "adminbackend"
        "id" => "shortcuts.show_shortcuts"
        "translation" => "Shortcuts tonen"
        "state" => 0
        "count" => 1
      ]
      // ...
```

**Comment by Rvanlaak** [comment]
ping @cedric-g does this sound like a plan to you? :wink:  could even be implemented BC by checking or the profiler collector does exist.

**Comment by cedric-g** [comment]
Hi, yes it could be an interesting feature. I'm also wondering if we can make a kind "page checker" that check if the page is completely translated for a given url.

**Comment by Rvanlaak** [comment]
Can I help you in this? I'm not known with the Angular ng-grid, so that should be related to the Symfony part ;-)

**Comment by cedric-g** [comment]
You can work on the Symfony side if you want. The ng-grid expect some JSON data formatted as the same way as in the [list action](https://github.com/lexik/LexikTranslationBundle/blob/master/Controller/RestController.php#L18).

So maybe you can add a route/action like this:
```yml
lexik_translation_list_missing:
    path:     /translations/{profile_token}
    defaults: { _controller: "LexikTranslationBundle:Rest:listMissing" }
    methods:  [GET]
```
If we get translations from the profiler data collector we won't have ids for each key/domain, but we need it to be able to update the translations from the grid. So we will have to query the database once we get missing key/domain pairs to get some complete row.
It also may happen that a key/domain pair does not already exist in the database (but we can handle this case later).

I've created a `list_missing_translations` branch, if you do some changes open a PR on this branch I will do the changes related to AngularJS.

**Comment by Rvanlaak** [comment]
:+1:

**Comment by Rvanlaak** [comment]
@cedric-g see #152

**Comment by Rvanlaak** [comment]
@cedric-g could you also add an edit button to the grid, so it is more clear that (double) clicking the grid enables translating. :+1:

**Comment by Rvanlaak** [comment]
ping @cedric-g

**Comment by cedric-g** [comment]
Yes I've not committed it yet but now the edit button will be always displayed.

**Comment by Rvanlaak** [comment]
:+1:

**Comment by Pierstoval** [comment]
After #152 is merged and @cedric-g pushed commits about the angular part, this issue should be closed, shouldn't it?

**Comment by rvanlaak** [comment]
@cedric-g this is fixed now? Feel free to close the issue.
