### ISSUE TITLE
Test in travis build doesn't work by memory limit with composer

### ISSUE THREAD

**Issue by shakaran** [lexik/LexikTranslationBundle#159]
Please check the travis builds, they are important for know if this project is stable in several php versions:

https://travis-ci.org/lexik/LexikTranslationBundle/jobs/72079230

**Comment by shakaran** [comment]
Suggestions:

    php -dmemory_limit=1G composer.phar update

Or:

    composer.phar --memory=1G update

Or use php.ini with memory_limit

Or could be useful:

    composer.phar install --prefer-source

Or create swap file:

	df -h 
	dd if=/dev/zero of=/swapfile bs=1M count=1024
	sudo dd if=/dev/zero of=/swapfile bs=1M count=1024
	mkswap /swapfile
	sudo chmod 600 /swapfile
	sudo mkswap /swapfile
	sudo swapon /swapfile
	echo 'echo "/swapfile  none  swap  defaults  0  0" >> /etc/fstab' | sudo sh

	free -m

**Comment by cedric-g** [comment]
Hi, thanks for the help, but since this change https://github.com/lexik/LexikTranslationBundle/commit/860d670ca9325e2c66f555224debffba0478a616 the [build is green](https://travis-ci.org/lexik/LexikTranslationBundle/builds/74421959).

**Comment by shakaran** [comment]
Wow, nice catch about the --dev param :+1: autoclosing my issue then :) Thanks!
