### ISSUE TITLE
Integration of 2.7 translator profiler

### ISSUE THREAD

**Issue by rvanlaak** [lexik/LexikTranslationBundle#165]
The Symfony 2.7 LTS release contains [new features that integrate the profiler with the translator](https://github.com/symfony/symfony/pull/14003). A new [list_missing_translations](https://github.com/lexik/LexikTranslationBundle/tree/list_missing_translations) branch was created to start making use of these features. There still are some TODOs left:

- [x] translation overview page
    - [x] show grid with number of translated items per domain per language
    - [x] add some sort of percentage, can we use the highest number of translation items as 100%?
    - [x] show message if there are no translations
- [ ] translation page
    - [x] get translations based on profiler token
    - [x] show message if there are no translations
    - [x] hide profiles after clicking 'all' button
    - [ ] somehow improve UX of the language checkboxes
- [ ] translations of new labels
- [ ] tests & docs

**Comment by Rvanlaak** [comment]
ping @cedric-g are we almost there? :+1:

**Comment by cedric-g** [comment]
not yet, I will try to find some time next week to work a bit on the bundle.

**Comment by Rvanlaak** [comment]
Was thinking about a decorator for the translator and the translation Twig extension, so we can integrate it with the grid. What about wrapping the translations in a span, and linking it with the search feature of the grid?

**Comment by cedric-g** [comment]
Why not, we can add an optional parameter to pass a trans-unit's id.

**Comment by Rvanlaak** [comment]
Does the ng grid already allow filtering on a get-parameter?

**Comment by cedric-g** [comment]
We can get the value in the grid action and pass it to the ng-grid (and so don't call the list action in this case)

**Comment by cedric-g** [comment]
@Rvanlaak I've added some percentages on the overview, it looks like:
![overview](https://cloud.githubusercontent.com/assets/570306/10314434/fdb55982-6c54-11e5-8edc-1028cd402d21.jpg)

**Comment by Rvanlaak** [comment]
Looks awesome! Will take a look at it later this week

**Comment by cedric-g** [comment]
@Rvanlaak I think I will merge the branch and create a new 3.1 version, others features/improvements can be done later.

**Comment by Rvanlaak** [comment]
Sound like a great plan to me

**Comment by rvanlaak** [comment]
@cedric-g this seems to be merged and released now right? Feel free to close this issue.
