### ISSUE TITLE
YAML-Export: set indentation

### ISSUE THREAD

**Issue by vaziuok** [lexik/LexikTranslationBundle#177]
Is it possible to define the indentation size of the tabs in the config.yml? We use in our company 4 tabs indetation for YAML-files and not 2.
On [this line](https://github.com/lexik/LexikTranslationBundle/blob/master/Translation/Exporter/YamlExporter.php#L36) you should insert then the value from the configuration.

**Comment by spike31** [comment]
Hi,

You can propose a PR if you have time ;)
