### ISSUE TITLE
Wrong path imported in database 

### ISSUE THREAD

**Issue by MisterGrouik** [lexik/LexikTranslationBundle#180]
Hey !
When I import my translations in database, the path in the table "lexik_translation_file" is something like "../C:wampwwwgithodorsrcTopoAppBundleResourcestranslations", which leads to error when I export them.
"Warning: file_put_contents(C:\wamp\www\git\hodor\app/../C:wampwwwgithodorsrcTopoAppBundleResourcestranslations/javascript.fr.xliff): failed to open stream: Invalid argument"

I work under Windows 7 and use the dev-master version of this bundle if that can help.

Thanks for your help

**Comment by MisterGrouik** [comment]
Analyzing getFileRelativePath from FileManager.php, I think this part is wrong :
// %kernel.root_dir% is always using "/" as directory separator
      dump('root dir'. $this->rootDir);
        $rootDirParts = explode('/', $this->rootDir);
        $filePathParts = explode('/', $filePath);

The comment is wrong. I dumped $this->rootDir and the separator was '\'.

**Comment by cedric-g** [comment]
Hi, I don't have any window, so can you have a try with the `fix_180` branch to check if you still have the error or not ?

**Comment by cedric-g** [comment]
@MisterGrouik have you tried with the `fix_180` branch ? is better or not ?

**Comment by Donjohn** [comment]
nop, this doesn't work either.

**Comment by Donjohn** [comment]
i copied the whole FileManager from fix_180 and use it, works fine now, import/export path is fixed. You can merge this file to master ;)

**Comment by cedric-g** [comment]
I've merged the fix (but not tagged yet).
