### ISSUE TITLE
The target-entity Lexik\Bundle\TranslationBundle\Model\TransUnitTranslation cannot be found in 'Lexik\Bundle\TranslationBundle\Model\TransUnit#translations'

### ISSUE THREAD

**Issue by ibasaw** [lexik/LexikTranslationBundle#188]
sf 2.8 on update database, just after install the bundle

**Comment by cedric-g** [comment]
Hi, I've set up the bundle one a 2.8 project and it works fine with Doctrine ORM and Doctrine MongoDB. Which Doctrine version are you using ?

**Comment by ibasaw** [comment]
"doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "^1.6",

**Comment by comemanu** [comment]
hello, unfortunatly the same error for me. 
sf 2.7
"doctrine/orm": "~2.4",
 "doctrine/doctrine-bundle": "~1.5"

tried to change the doctrine versions but whithout success.

**Comment by ibasaw** [comment]
news ?

**Comment by kasparsklavins** [comment]
Same with symfony 3.1

**Comment by kasparsklavins** [comment]
The problem is with `a2lix/i18n-doctrine-bundle`.
It injects its own mapping information.

https://github.com/a2lix/I18nDoctrineBundle/blob/master/Doctrine/ORM/EventListener/DoctrineListener.php#L66

**Comment by llukaszb** [comment]
Eh :-). I spent a lot of time to found it. Do you find some solution for it ?

**Comment by ibasaw** [comment]
i don't use it...

**Comment by kasparsklavins** [comment]
@llukaszb In the entities I use, I implemented a `TranslatableInterface` and overwrote `DoctrineListener` to look for that interface instead of just check if it has a translations property.
