### ISSUE TITLE
Hitting enter to save on v3.1.1 does not work?

### ISSUE THREAD

**Issue by arendjantetteroo** [lexik/LexikTranslationBundle#190]
Due to a mongo issue i've updated to v3.1.1 and now hitting enter after changing a translation message no longer triggers a save action. 

I've now tried 3.0 which has the same Mongo fix fortunataly and that works fine. I'm not sure what changed between 3.0 and 3.1.1. Does anybody have the same issues with the latest release? 

Tried with both the ng-table from the release as with latest ng-table from bower. Both work fine on 3.0, not on 3.1.1. 

What can i do to help debug this?

**Comment by sysdoeurosat** [comment]
+1
I had same problem. Temporary downgrade to 3.0 solved it
