### ISSUE TITLE
cannot export database: "No exporter found for "xml" format."

### ISSUE THREAD

**Issue by tejon-melero** [lexik/LexikTranslationBundle#208]
First of all thank you for your great bundle. 
I am  using version ~3.1 of this bundle with symfony 2.7
I was able to install the bundle, install the routes and import the text files into the database without any problem I can even save the changes in the database on the translation pages, but as soon as I want to export the changes back into my language files I get the following error: 

Exporting "../../translations/validators.en.xlf":
 OutputPath "/../../Resources/translations":
 OutputFile "/./translations/validators.en.xml":
Output file: /././translations/validators.en.xml
1 translations to export: "No exporter found for "xml" format." 

I have installed the following php packages on my system (Ubuntu 14.04) 
libssh2-php					
php-apc						
php-pear					
php-xml-parser					
php5						
php5-apcu					
php5-cli					
php5-common					
php5-curl					
php5-dev					
php5-fpm					
php5-gd						
php5-imagick					
php5-intl					
php5-json					
php5-ldap					
php5-mcrypt					
php5-readline	

Do you have any idea where this error could come from (maybe a missing php extension?) Thank you very much in advance for your help.

**Comment by cedric-g** [comment]
Hi, try with `xliff` or `xlf` instead of `xml`.
