### ISSUE TITLE
dev_tools create_missing - what am *I* missing :( 

### ISSUE THREAD

**Issue by PhilETaylor** [lexik/LexikTranslationBundle#212]
ok so the reason I wanted this bundle was so I could put a load of 

{{ 'blah.blah.blah'|trans }}

in my twig's and then load the page - see the "blah.blah.blah" in the page, and then go to this bundles Grid to see the key "blah.blah.blah" and then I could input my translations, and then export back to xliff files... (cant do that? see #211 ) 

it seems... that after rendering the "blah.blah.blah" in the template, I go to the Translations Grid and search for key blah.blah.blah - and I get No rows... 

If I then select Data Source Profiler, I can see the blah.blah.blah key in the last profile - is this the way its meant to be?

So then I translate the blah.blah.blah into three languages - blah blah and blah, and now I want to export this to xliff files for deployment... I run lexik:translations:export command but nothing is written to my xliff files.. I was expecting it to populate the files from the new entries in the database... 

Do I just need more 🍕 ? or am I expecting this to do something it is not designed for? 

Im now stuck with several hundred strings in the db and no way to dump them to files :-(

**Comment by PhilETaylor** [comment]
ok talking to my self here.. .I see that when I "ADD NEW TRANSLATIONS" using the dedicated form in the admin of your bundle - these CAN be exported fine. 

However when I find a key that has been automatically added by create_missing, I find it in the profile - this adds it to lexik_trans_unit table - I then EDIT this row using the ajax row that turns into input boxes - I translate to en fr de - I then click the save button at the end of the row and this inserts the rows into lexik_trans_unit_translations - BUT there is a NULL for the file_id !!! This is the BUG 🐛 !!!

Without that file_id column being populated these translations will be be exported.

My workaround at the moment is to manually update the db setting a 42 (ironic) as the file_id value - and then doing an export populates my files correctly. 

So I think this is an addressable bug :)

**Comment by cedric-g** [comment]
Hi, I fixed it on master, new translations created from a profile are now linked to a file.
You can change the default file format:
```yml
lexik_translation:
    dev_tools:
        file_format: yml # xlf, ...
```

**Comment by PhilETaylor** [comment]
@cedric-g Excellent - I'll update and test this for you today. Thanks.

**Comment by kasparsklavins** [comment]
Is it possible to achieve the same effect but save it to database, with devtools disabled?
