### ISSUE TITLE
utf8mb4 encoding

### ISSUE THREAD

**Issue by zeckon** [lexik/LexikTranslationBundle#226]
We are using a db with utf8mb4 encoding. 

While creating the tables we get the error 'max key length is 767 bytes' as there are some varchar(255) columns with indexes. 

How can we override these properties (such as key_name,domain in  lexik_trans_unit) so we can define them as the max allowed size (which is varchar(191))

Thanks.

**Comment by cedric-g** [comment]
Hi, maybe you can try to listen the doctrine's loadClassMetadata event and change the mapping according to your needs.

**Comment by zeckon** [comment]
actually i think it would be better if it is fixed in the bundle instead of extending/overriding mapping in the app since even symfony suggests using utf8mb4 at http://symfony.com/doc/current/doctrine.html

**Comment by zeckon** [comment]
and also fosuserbundle recently fixed this kind of issue https://github.com/FriendsOfSymfony/FOSUserBundle/commit/c54e42a44c0024124ddac02d6482abd4740bb7c1

**Comment by spike31** [comment]
The problem is that we have to update each tables and each columns.
We need a PR ! :)
