### ISSUE TITLE
Attempted to call function "apc_exists" 

### ISSUE THREAD

**Issue by h3llr4iser** [lexik/LexikTranslationBundle#237]
I am trying to invalidate cache in prod eviroment and I has this error:
"Attempted to call function "apc_exists" from namespace "Lexik\Bundle\TranslationBundle\Translation"." at /var/www/edibon.com/httpdocs/releases/20170119181743/vendor/lexik/translation-bundle/Translation/Translator.php line 110

I have installed apcu in ubuntu php 7

apcu
APCu Support	Enabled
Version 	5.1.8
APCu Debugging 	Disabled
MMAP Support 	Enabled
MMAP File Mask 	no value
Serialization Support 	php
Build Date 	Jan 20 2017 10:20:51
Directive	Local Value	Master Value
apc.coredump_unmap	Off	Off
apc.enable_cli	On	On
apc.enabled	On	On
apc.entries_hint	4096	4096
apc.gc_ttl	3600	3600
apc.mmap_file_mask	no value	no value
apc.preload_path	no value	no value
apc.serializer	php	php
apc.shm_segments	1	1
apc.shm_size	32M	32M
apc.slam_defense	On	On
apc.smart	0	0
apc.ttl	0	0
apc.use_request_time	On	On
apc.writable	/tmp	/tmp

**Comment by cedric-g** [comment]
Hi, have you tried to also install the APCu Backwards Compatiblity module ?

**Comment by h3llr4iser** [comment]
thx, I have installed and now It works:
https://serverpilot.io/community/articles/how-to-install-the-php-apcu-bc-extension.html

**Comment by grimgit** [comment]
Hi,
APCu Backwards Compatiblity module isn't a solution in a modern PHP 7+opcache+acpu.

This is the code with the issue:

```php    
protected function invalidateSystemCacheForFile($path)
    {
        if (ini_get('apc.enabled')) {
            if (apc_exists($path) && !apc_delete_file($path)) {
                throw new \RuntimeException(sprintf('Failed to clear APC Cache for file %s', $path));
            }
        } elseif ('cli' === php_sapi_name() ? ini_get('opcache.enable_cli') : ini_get('opcache.enable')) {
            if (!opcache_invalidate($path, true)) {
                throw new \RuntimeException(sprintf('Failed to clear OPCache for file %s', $path));
            }
        }
    }
```

Installing apcu-bc we are in the first condition, there is no apc cache because apcu don't cache opcode (and apc_delete_file() function doesn't exists neither with apcu-bc), the opcache check is skipped and the cache not cleared.

A solution could be:
```php 
if (ini_get('apc.enabled') && function_exists('apc_delete_file')) {
```
