### ISSUE TITLE
[Feature] Cache system

### ISSUE THREAD

**Issue by pesseyjulien** [lexik/LexikTranslationBundle#249]
Hi,

First I want to say thanks for this great bundle, it helps me a lot and it's working great.

I do have a small question though, do you think it would be feasible to let the user choose it's caching system (ie, redis, memchache,...). I'm asking this because, for example, I'm using the translations on a website but I administer the translations from a back-office. So clearing the cache from the b-o, does not affect the website. I know there is an option to auto-clean the cache, but it's not as convenient. 

Thanks,
Julien

**Comment by cedric-g** [comment]
Hi, translations cache files are managed at the component level, not by the bundle it self.

**Comment by pesseyjulien** [comment]
Hi,

Thanks for your feedback. Would it be possible to manage cache files from redis ?

**Comment by cedric-g** [comment]
Maybe in some future versions, see https://github.com/symfony/symfony/issues/20430
