### ISSUE TITLE
Translator changed in symfony3.3

### ISSUE THREAD

**Issue by arendjantetteroo** [lexik/LexikTranslationBundle#258]
From https://github.com/symfony/symfony/blob/master/UPGRADE-3.3.md

The Symfony\Bundle\FrameworkBundle\Translation\Translator constructor now takes the default locale as 3rd argument. Not passing it will trigger an error in 4.0.

As the Lexik Translator object is configured with extra values, i get a "Array expected, got Object" or "Array expected, got String" on the last argument passed in the container configuration  
<argument type="service" id="session" on-invalid="ignore" />

Just adding the default locale does not seem to work properly in a local config.xml, after changing it i don't get a service error anymore but the translations are no longer appearing on the screen.

**Comment by endroid** [comment]
Same issue here

**Comment by chagriali** [comment]
I have the same issue

**Comment by frenchcomp** [comment]
I have the same issue

**Comment by insekticid** [comment]
https://github.com/lexik/LexikTranslationBundle/pull/257

**Comment by macroprog** [comment]
Hello,
Do you know when the fix for this bug will be merged into the master branch ? 
I'm stuck as i have updated my symfony version and this bundles doesn't work anymore.
Thank you

**Comment by FriTOol** [comment]
+1

**Comment by klausbreyer** [comment]
+1

**Comment by antoinearrive** [comment]
+1

**Comment by ajaunasse** [comment]
+1

**Comment by GregHubs** [comment]
+1

**Comment by arendjantetteroo** [comment]
Please stop +1 this issue and test out the solution in #260 if you want to help.

**Comment by spike31** [comment]
+1 @arendjantetteroo 
@cedric-g need to fix his PR, bug with sf 3.2

**Comment by GregHubs** [comment]
#260 gave this error 
` Fatal error: Cannot declare class AppKernel, because the name is already in use in C:\...\vendor\lexik\translation-bundle\Tests\app\AppKernel.php on line 102`

**Comment by spike31** [comment]
@GregHubs Please comment the PR directly ;)

**Comment by GregHubs** [comment]
@spike31 done !
