### ISSUE TITLE
Symfony 3.3.5 Warning: Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by denya-vs** [lexik/LexikTranslationBundle#264]
When I updated symfony to version 3.3.5 and clear cache. I catch exception about definition:
![](http://img.netpeak.ua/denya/2017-07-25_34c691.png)

**Comment by davidskaraboo** [comment]
What was your previous version?

srry for english :)

**Comment by denya-vs** [comment]
1.first my version is 3.1
2. Then I update symfony to 3.2. and all worked is correct.
3. Then I update symfony to 3.3.5 and catch excetion
Type error: Argument 5 passed to Symfony\Bundle\FrameworkBundle\Translation\Translator::__construct() must be of the type array, object given, called in /var/www/var/cache/dev/appDevDebugProjectContainer.php on line 2860
![](http://img.netpeak.ua/denya/2017-07-25_ce6d75.png)
4. Then I find pull request and commit when this exception fixed, and chechout to dev-master 9ae3d76
5. Then I catch new exception, described below.

**Comment by denya-vs** [comment]
#265

**Comment by pawelkolanowski** [comment]
+1

**Comment by cioll** [comment]
👍

**Comment by Growiel** [comment]
The patch at #265 is working fine for me.

Can we please have to merged AND a tag made ? All this messing around with the composer.json and relying on dev-master makes me unconfortable.

Thanks.

**Comment by acassan** [comment]
+1 need merge

**Comment by acassan** [comment]
Fix build by this one: 

```
$className = sprintf('lexik_translation.%s.translation_storage.class', $storage);
$storageDefinition->setArguments($args);
$storageDefinition->setClass('%'.$className.'%');
```

Missing this line on your build: 
`$storageDefinition->setArguments($args);`

**Comment by marcossegovia** [comment]
+1 need merge

**Comment by sdieunidou** [comment]
fixed
