### ISSUE TITLE
New tag creation

### ISSUE THREAD

**Issue by eko** [lexik/LexikTranslationBundle#268]
Hello,

We are upgrading our application to Symfony 3.3 but we can see that the last stable tag was `4.0.2` tagged on `2017-01-18` (which is old now).

Some work have been done to reflect new Symfony 3.3 API changes in master branch (commit https://github.com/lexik/LexikTranslationBundle/commit/35cf0d09d4bb25583e5b899a5744bfe0a7a8486d) but we cannot take the benefit of it unless using `dev-master` version which is not a really great way to deal with versioning.

Could you tag a new stable release please?

**Comment by eko** [comment]
What do you think @cedric-g?

**Comment by arendjantetteroo** [comment]
What can we do to help this bundle into 3.3 territory? 
3.2.13 is the latest for 3.2 so i rather would have a tagged lexik translation bundle for 3.3 to move over.

**Comment by acrobat** [comment]
Ping @cedric-g

**Comment by sdieunidou** [comment]
new tag created

**Comment by eko** [comment]
You rock guys 🎉  Thank you!

**Comment by arendjantetteroo** [comment]
Thanks!
