### ISSUE TITLE
Symfony 4 Support - problem due to private services

### ISSUE THREAD

**Issue by gci-brandlab** [lexik/LexikTranslationBundle#316]
As services in the symfony container are now private, we get the following error message:

The "lexik_translation.translation_storage" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

**Comment by aurimas535** [comment]
Found this workaround. Add this service definition to your services.yaml

`lexik_translation.translation_storage:
        class: Lexik\Bundle\TranslationBundle\Storage\DoctrineORMStorage
        public: true
        arguments:
            $registry: '@doctrine'
            $managerName: 'default'
            $classes:
                trans_unit: Lexik\Bundle\TranslationBundle\Entity\TransUnit
                translation: Lexik\Bundle\TranslationBundle\Entity\Translation
                file: Lexik\Bundle\TranslationBundle\Entity\File`

**Comment by MrNicodemuz** [comment]
Same thing happens also when you enable the dev tools:

    lexik_translation:
        dev_tools:
            enable: true
            create_missing: true
            file_format: yml

In this case a similar error will appear:

    The "lexik_translation.token_finder" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

**Comment by MrNicodemuz** [comment]
A similar workaround for the above issue:

    services:
        lexik_translation.token_finder:
            class: Lexik\Bundle\TranslationBundle\Util\Profiler\TokenFinder
            public: true
            arguments:
                $profiler: '@profiler'
                $defaultLimit: 15
