### ISSUE TITLE
BC Break on v4.0.9

### ISSUE THREAD

**Issue by rmasclef** [lexik/LexikTranslationBundle#318]
Adding the field `modifiedManually` in Translation model makes database insertion fail

```
An exception occurred while executing 'SELECT l0_.key_name AS key_name_0, l0_.domain AS domain_1, l0_.created_at   
  AS created_at_2, l0_.updated_at AS updated_at_3, l0_.id AS id_4, l1_.locale AS locale_5, l1_.content AS content_6  
  , l1_.created_at AS created_at_7, l1_.updated_at AS updated_at_8, l1_.modified_manually AS modified_manually_9, l  
  1_.id AS id_10 FROM lexik_trans_unit l0_ LEFT JOIN lexik_trans_unit_translations l1_ ON l0_.id = l1_.trans_unit_i  
  d WHERE l0_.domain = ? AND l1_.locale = ?' with params ["FrontOffice", "en"]:                                      
                                                                                                                     
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l1_.modified_manually' in 'field list'  
```

The user needs to add that field in its DB in order to fix this error.
So, I this is a BC Break :+1:

Can someone please create a file like UPGRADE.md that explains the BC break ?
To be more semver compliant, I think we should create a major tag :+1: (but then, we need to find a better fix about https://github.com/lexik/LexikTranslationBundle/pull/261)

https://github.com/lexik/LexikTranslationBundle/blob/v4.0.8/Model/Translation.php
vs
https://github.com/lexik/LexikTranslationBundle/blob/v4.0.9/Model/Translation.php

**Comment by spike31** [comment]
Hello too,

And I do not consider it a BC break. When you update a bundle that uses a database, you probably have to test and see if there is a migration or not to do. 

A real BC break, I might be wrong but, could be if we had removed an important field from the database, here we simply add a new field. 

Should we have to create a UPGRADE.md just for tell you that you have to update your database?
Thats your job to run tests and check database errors.

But thank you for participating in open source by pointing out a problem, it helps us maintain our bundles.

**Comment by rmasclef** [comment]
Sorry for that -> Hello @spike31 :+1: 

I understand your point, and yes, it can be tricky to determine if something is a BC break or not.
We actually detected that while testing :)

I was just really surprised not to have any information (like an UPGRADE.md) explaining that we might encounter errors when updating to that version.
