### ISSUE TITLE
Ability to remove single locale translation/set null

### ISSUE THREAD

**Issue by daum** [lexik/LexikTranslationBundle#325]
It doesn't appear that form the admin UI you can remove the translation for only a single locale due to: https://github.com/lexik/LexikTranslationBundle/blob/master/Manager/TransUnitManager.php#L165 .  What we're trying to do is set a translation to null so it will go back to our fall back locales, but it doesn't appear that is possible.  Can you confirm that?

Thanks!

**Comment by bartmcleod** [comment]
I can confirm that this does not work. When blanking out a translation and saving the row, the cleared translation re-appears

**Comment by bartmcleod** [comment]
But, while testing this PR, although it works, I found that it seems to be designed differently, probably for a reason: if you want to clear an individual translation, you can do so by clicking the trash icon on a row and then click the cross next to the individual translation you want to delete and then click the cancel icon to keep the remainder of the row.  So I am not sure we should merge the solution when there is already a way to do this.
