### ISSUE TITLE
Travis builds broken?

### ISSUE THREAD

**Issue by phpwutz** [lexik/LexikTranslationBundle#363]
Hi, I've just submitted a PR and wondered why the CI build broke.

This is the broken build:
https://travis-ci.org/lexik/LexikTranslationBundle/builds/626345459?

Apparently this is not only happening for me:
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

The issue seems to exist at least since August 2019 (older broken build from someone else:  https://travis-ci.org/lexik/LexikTranslationBundle/builds/580149758?utm_source=github_status&utm_medium=notification )

I'm not really knowledegable in travis, so maybe someone else can take a look and try to fix the CI? :)
Happy to contribute more PRs otherwise!

**Comment by bartmcleod** [comment]
This is solved for the 3.4, 4.4 and master branches. Existing PR's should be based on any of these branches, depending on which Symfony version they are targeting. The Symfony version roughly matches the branch name. The master branch is for Symfony 5.
