### ISSUE TITLE
Broken exporter

### ISSUE THREAD

**Issue by nithiz** [lexik/LexikTranslationBundle#385]
Hello,

Running the exporter will give me an error because the `$container->hasDefinition('lexik_translation.exporter_collector')` check always fails. 

When i change this to `$container->hasDefinition('Lexik\Bundle\TranslationBundle\Translation\Exporter\ExporterCollector')` everything works as expected.

Am i doing something wrong or is this a bug?

**Comment by bartmcleod** [comment]
This is likely a bug, although I tested with Symfony 5.2 and the export worked. I noticed however that this `hasDefinition` call still exists for old style service definitions and that does not seem to work, I had to fix acouple of them. This likely is just another of those. Will label it bug.

**Comment by bartmcleod** [comment]
@nithiz which version did you install? I do get an issue with the exporter related to the collector, but it is different.

**Comment by bartmcleod** [comment]
@nithiz Please confirm that this is fixed with v5.0.1 and close the issue.

**Comment by nithiz** [comment]
@bartmcleod Thanks for the update, i will check it out later today :)

**Comment by nithiz** [comment]
@bartmcleod Thanks! It's working now, i was using 5.0.0 before.
