### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by mleko64** [lexik/LexikTranslationBundle#390]
Hello,
Do you plan to support for PHP8?

**Comment by bartmcleod** [comment]
Yes, but I looked into it about two months ago and some depencies will not install, because they have a hard php .7x requirement. Until those are updated, we are stuck.

**Comment by mleko64** [comment]
Which one? I looked into composer.json and check all dependencies on packegist.org and all supports PHP8.

**Comment by bartmcleod** [comment]
It is great that you have done this research again. Packages may have been updated since I last checked. I will look into it.

**Comment by mleko64** [comment]
Great :)

**Comment by HecFranco** [comment]
Hello,
Does the bundle already support PHP8?
