### ISSUE TITLE
Outdated Angular.js used

### ISSUE THREAD

**Issue by otskarli** [lexik/LexikTranslationBundle#392]
Will the latest angular be supported any time soon or any plans for it in the future? 
tried updating the file myself, but everything breaks.

**Comment by bartmcleod** [comment]
@otskarli Can you elaborate a bit on that? I am maintaining the project on an as needed / have time bases but I do not know everything about it. So, for example, do we use an older angular version currently? Which is "the file"?

**Comment by otskarli** [comment]
Hey, the file is Resources/views/layout.html.twig 
it uses //ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.min.js
if i use https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular.min.js
everything breaks

**Comment by bartmcleod** [comment]
This has been solved, we now use Angular 1.8.2
