### ISSUE TITLE
Update the project's description

### ISSUE THREAD

**Issue by alexislefebvre** [lexik/LexikTranslationBundle#393]
Hello,
please update the description to list the supported Symfony version.

It mentions Symfony2:

> ![image](https://user-images.githubusercontent.com/2071331/119546635-6c04de80-bd94-11eb-88d8-1b46183db898.png)

**Comment by bartmcleod** [comment]
@lexikteam  I cannot edit that description. Can you?

**Comment by spike31** [comment]
@bartmcleod 

Ok I can removed the "2" :smile:
