### ISSUE TITLE
Bump composer for symfony 5.3

### ISSUE THREAD

**Issue by nicolasricci** [lexik/LexikTranslationBundle#394]
Hello,

Is there any specific issue to bump the `symfony/framework-bundle` package requirement to 5.3? 

If not could could you please upgrade the composer file?

Many thanks
Nicolas

**Comment by bartmcleod** [comment]
Hi @nicolasricci I don't think there is an issue. Just when I last tested things, Symfony was at 5.2. So should I add ^ for 5.2 and up? Not sure what you need exactly.

**Comment by bartmcleod** [comment]
For Symfony 5.3, use the 5.3 branch. If there are still issues, let me know. If I should create a specific v5.3 branch, also, let me know.
