### ISSUE TITLE
Incompatibility with doctrine/dbal

### ISSUE THREAD

**Issue by andriusvo** [lexik/LexikTranslationBundle#402]
Hello,

In `Lexik\Bundle\TranslationBundle\Storage\DoctrineORMStorage` there is a method `getDriver()->getName()`. `getName()` method is deprecated in `doctrine/dbal` package and is not compatible with `3.0` version of `doctrine/dbal`. BC break described here:
https://github.com/doctrine/dbal/blob/3.1.x/UPGRADE.md

**Comment by Knallcharge** [comment]
The upgrade-document suggests "For referencing the driver, use its class name.", I have created a pull request that does just that and works with both dbal 2 and 3, please check.

**Comment by bartmcleod** [comment]
@Knallcharge please use `instanceof` instead of `get_class`

**Comment by Knallcharge** [comment]
Updated my pull-request.
