### ISSUE TITLE
Symfony 6 support?

### ISSUE THREAD

**Issue by nicodemuz** [lexik/LexikTranslationBundle#406]
Anyone started looking at supporting Symfony 6 yet? Any changes required apart from bumping the composer dependencies?

**Comment by tuxes3** [comment]
it was super fast work. the services.xml needs a redo... but it works in symfony 6 and php 8. 

https://github.com/tuxes3/LexikTranslationBundle

**Comment by Seb33300** [comment]
Can you please create a pull request?

**Comment by tuxes3** [comment]
https://github.com/lexik/LexikTranslationBundle/pull/412

**Comment by bartmcleod** [comment]
We support SF 6 now
