### ISSUE TITLE
Translations +intl-icu support

### ISSUE THREAD

**Issue by ice-devel** [lexik/LexikTranslationBundle#430]
Hi,

I'm having an issue when trying to use ICU syntax for translations.

I have added the "+intl-icu" prefix to the translation filename and used the command "console lexik:translations:import" to import translations stored in yaml format with ICU syntax. The translations are successfully imported into the database and can be accessed via the LexikTranslationBundle web interface (the domain created is "messages+intl-icu").

However, when I try to use these translations, I'm unable to access them using the "messages" domain with ICU syntax, the translation key is displayed. 

Obviously, all is fine if I let the translation key in the file

I'm not sure what I'm doing wrong or how to fix this issue, does this bundle support the ICU syntax ?

Any help would be greatly appreciated.

**Comment by bartmcleod** [comment]
@ice-devel Can you maybe add an example file to this issue, so that I can try it for myself? I think we should support it if it is valid.

**Comment by ice-devel** [comment]
@bartmcleod So sorry, it works. I clicked "Invalidate cache" button after import coommand, and event if I was in dev mode, I had to clear my symfony dev cache too :/ 

:)

**Comment by bartmcleod** [comment]
No worries :-)
